export declare const ALGORAND_ADDRESS_LENGTH = 58;
export declare const VALID_ALGORAND_ADDRESS = "CINCNAPB2RLDUCS3EVDLURZZD742TMWRQEZ4CBEWF2QMOYXMH6RWRZEIEA";
export declare const BASE32_RFC_4648_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
